### ISSUE TITLE
Generalize to share defaults between crates

### ISSUE THREAD

**Issue by TedDriggs** [TedDriggs/serde_default#1]
See dtolnay/request-for-implementation#4 for original context.

`serde`, `derive_builder`, and `darling` all have essentially the same implementation of the `default` property to support field-level defaulting. Having one crate that exposes a `#[default(...)]` property which all 3 can look to.

# Proposal
This crate would declare a `BetterDefault` derive-mode-macro that reads the `default` attribute. `serde`, `derive_builder`, `darling`, and any others would add the `default` attribute to the list of ones they read as well.

`#[serde(default = "...")]` would override `#[default(default = "...")]`, supporting the use-case of being more specific in different contexts.

The syntax of this crate's attribute would be very stable; the serde path model has broad adoption and hasn't required modification. As a result, this crate would rapidly ship a 1.0, and no 2.0 is ever expected.

cc @dtolnay for thoughts

**Comment by dtolnay** [comment]
Serde is going to be very conservative about adopting non-Serde attributes, but I am not opposed to it in the long term if it becomes a frequent request.

`#[default = "..."]` would be preferable IMO.
