### ISSUE TITLE
Consider naming exported macro "Derive_serde"

### ISSUE THREAD

**Issue by TedDriggs** [TedDriggs/serde_default#2]
In dtolnay/request-for-implementation#4, @dtolnay pointed out that there is no such trait as `SerdeDefault`, and suggested `Default_serde` instead.

My first reaction is that `Default_serde` looks like a typo or stylistic error. That said, there is prior art of non-PascalCase derives, such as [derive(is_enum_variant)](https://crates.io/crates/derive_is_enum_variant).

It could be confusing that no trait exists, but there is precedent for derives that don't map to traits:
* `derive(Builder)` produces a new struct and no trait
* [`strum`](https://docs.rs/strum/0.13.0/strum/) produces a variety of impls that don't match the PascalCase names in the `derive`
* [`derive_state_machine_future`](https://crates.io/crates/state_machine_future) also has a PascalCase derive name that doesn't map to a real trait.
* `derive(FromVariants)` produces multiple impls of the `From` trait (though I wrote that crate so I'm not sure it counts)

**Comment by dtolnay** [comment]
That's fair, feel free to close the issue. Thanks for sharing your thoughts!

**Comment by TedDriggs** [comment]
Ended up choosing `DefaultFromSerde` so that it's still PascalCase but the name does prioritize the derived trait first.
