### ISSUE TITLE
Status?

### ISSUE THREAD

**Issue by yujqiao** [TedDriggs/serde_default#3]
Thanks for your work!

It's handy to have https://github.com/dtolnay/request-for-implementation/issues/4 usable. What do you think?

**Comment by TedDriggs** [comment]
I must confess I haven't had reason to use this in a long time - is it currently broken?

**Comment by yujqiao** [comment]
This crate is unpublished. So it's not easy for people to use, since a crate with git dependency can't be published



---Original---
From: "Ted ***@***.***&gt;
Date: Fri, Jan 14, 2022 23:49 PM
To: ***@***.***&gt;;
Cc: "Yujia ***@***.******@***.***&gt;;
Subject: Re: [TedDriggs/serde_default] Status? (Issue #3)




 
I must confess I haven't had reason to use this in a long time - is it currently broken?

**Comment by TedDriggs** [comment]
Oops. I will do that today. I am going to first update the dependencies and edition.

**Comment by TedDriggs** [comment]
I've updated the crate and am about to publish. Please be advised the trait name is now `DefaultFromSerde`

**Comment by TedDriggs** [comment]
Crate is now published.
